### ISSUE TITLE
Write code for sending notifications

### ISSUE THREAD

**Issue by roerohan** [roerohan/Juvo-App#2]
https://github.com/roerohan/Juvo-App/blob/fed34c379c4e9a0e8f6d67c444f8d94950823c05/app/src/main/java/roerohan/com/myapplication/MainActivity.java#L43

- Write code to send notifications

**Comment by sdesani** [comment]
Is this about using the `sendNotification()` method which is on L143 or a new notification method/code needs to be written ?

**Comment by roerohan** [comment]
The `sendNotification()` function probably has some sort of a bug, I don't remember since it's a very old repository.
You may write a new method, or fix the existing one; whichever is more convenient for you!

Thanks for your contribution @sdesani

**Comment by sdesani** [comment]
@roerohan , added https://github.com/roerohan/Juvo-App/pull/3
